/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package com.example.springcamelsalesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist OtherGeocodeAccuracy
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Contact_OtherGeocodeAccuracyEnum {

    // Address
    ADDRESS("Address"),

    // Block
    BLOCK("Block"),

    // City
    CITY("City"),

    // County
    COUNTY("County"),

    // ExtendedZip
    EXTENDEDZIP("ExtendedZip"),

    // NearAddress
    NEARADDRESS("NearAddress"),

    // Neighborhood
    NEIGHBORHOOD("Neighborhood"),

    // State
    STATE("State"),

    // Street
    STREET("Street"),

    // Unknown
    UNKNOWN("Unknown"),

    // Zip
    ZIP("Zip");

    final String value;

    private Contact_OtherGeocodeAccuracyEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Contact_OtherGeocodeAccuracyEnum fromValue(String value) {
        for (Contact_OtherGeocodeAccuracyEnum e : Contact_OtherGeocodeAccuracyEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }
}
