/*
 * Salesforce Query DTO generated by camel-salesforce-maven-plugin
 */
package com.example.springcamelsalesforce.dto;

import org.apache.camel.component.salesforce.api.dto.AbstractQueryRecordsBase;

import java.util.List;
import javax.annotation.Generated;

/**
 * Salesforce QueryRecords DTO for type Contact
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public class QueryRecordsContact extends AbstractQueryRecordsBase<Contact> {
}
