/*
 * Salesforce Query DTO generated by camel-salesforce-maven-plugin
 */
package com.example.springcamelsalesforce.dto;

import org.apache.camel.component.salesforce.api.dto.AbstractQueryRecordsBase;

import java.util.List;
import javax.annotation.Generated;

/**
 * Salesforce QueryRecords DTO for type Account
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public class QueryRecordsAccount extends AbstractQueryRecordsBase<Account> {
}
